
-- 応募テーブル
-- DROP TABLE IF EXISTS t_apply;
CREATE TABLE t_apply (
	id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
	relation_data_type int NOT NULL COMMENT '関連データ種別',
	relation_data_id bigint NOT NULL COMMENT '関連データID',

	data_type int NOT NULL COMMENT 'データタイプ',
	post_title TEXT COMMENT '記事タイトル',
	post_sub_title TEXT COMMENT '記事サブタイトル',
	post_content TEXT COMMENT '記事本文',
	post_link TEXT COMMENT '記事リンク',
	post_link_text TEXT COMMENT '記事リンクテキスト',
	post_status int DEFAULT 0 COMMENT '記事ステータス',
	order_number int COMMENT 'ソート順',
	post_date DATE COMMENT '登録日',
	new_icon_end_date DATE COMMENT 'NEWアイコン表示終了日',
	publish_end_date DATE COMMENT '掲載終了日時',
	draft_flg varchar(1) DEFAULT '0' COMMENT '下書きフラグ',
	-- 追加カラムはここに記述

	free_form_id BIGINT NOT NULL COMMENT 'メールフォームID',
	name TEXT COMMENT '名前',
	furigana TEXT COMMENT 'フリガナ',
	company_name TEXT COMMENT '企業団体名',
	position TEXT COMMENT '役職等',
	email TEXT COMMENT 'Eメールアドレス',
	phone_number varchar(20) COMMENT '電話番号',
	postal_code1 varchar(10) COMMENT '郵便番号',
	postal_code2 varchar(10) COMMENT '郵便番号',
	place TEXT COMMENT '住所',
	other_inquiry TEXT COMMENT 'その他お問い合わせ',
	optional_form1  TEXT COMMENT '追加項目1',
	optional_form2  TEXT COMMENT '追加項目2',
	optional_form3  TEXT COMMENT '追加項目3',
	optional_form4  TEXT COMMENT '追加項目4',
	optional_form5  TEXT COMMENT '追加項目5',
	optional_form6  TEXT COMMENT '追加項目6',
	optional_form7  TEXT COMMENT '追加項目7',
	optional_form8  TEXT COMMENT '追加項目8',
	optional_form9  TEXT COMMENT '追加項目9',
	optional_form10 TEXT COMMENT '追加項目10',
	optional_form11 TEXT COMMENT '追加項目11',
	optional_form12 TEXT COMMENT '追加項目12',
	optional_form13 TEXT COMMENT '追加項目13',
	optional_form14 TEXT COMMENT '追加項目14',
	optional_form15 TEXT COMMENT '追加項目15',
	optional_form16 TEXT COMMENT '追加項目16',
	optional_form17 TEXT COMMENT '追加項目17',
	optional_form18 TEXT COMMENT '追加項目18',
	optional_form19 TEXT COMMENT '追加項目19',
	optional_form20 TEXT COMMENT '追加項目20',
	optional_form21 TEXT COMMENT '追加項目21',
	optional_form22 TEXT COMMENT '追加項目22',
	optional_form23 TEXT COMMENT '追加項目23',
	optional_form24 TEXT COMMENT '追加項目24',
	optional_form25 TEXT COMMENT '追加項目25',
	optional_form26 TEXT COMMENT '追加項目26',
	optional_form27 TEXT COMMENT '追加項目27',
	optional_form28 TEXT COMMENT '追加項目28',
	optional_form29 TEXT COMMENT '追加項目29',
	optional_form30 TEXT COMMENT '追加項目30',

	del_flg varchar(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ',
	insert_user varchar(50) COMMENT '登録ユーザー',
	insert_datetime DATETIME COMMENT '登録日時',
	update_user varchar(50) COMMENT '更新ユーザー',
	update_datetime DATETIME COMMENT '更新日時',
	PRIMARY KEY(id)
) ENGINE = InnoDB COMMENT '応募テーブル';
ALTER TABLE `t_apply` CONVERT TO CHARACTER SET utf8;
