

INSERT INTO t_free_form ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, to_email, to_email_2, from_email, from_label, mail_subject, confirm_message, mail_signature, del_flg, insert_user, insert_datetime, update_user, update_datetime ) 
VALUES (1,0,0,100,'お問い合わせ','','','','',null,null,'2013-05-01',null,null,'0','ta-ando@tiki.ad.jp','','','','','',null,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');


INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (1,100,1,101,null,null,null,null,null,null,0,null,null,null,'0',1,'basic','お名前','','form_use',1,1,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (2,100,1,101,null,null,null,null,null,null,1,null,null,null,'0',2,'basic','フリガナ','','form_use',1,1,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (3,100,1,101,null,null,null,null,null,null,2,null,null,null,'0',3,'basic','会社・団体名','','form_use',1,1,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (4,100,1,101,null,null,null,null,null,null,3,null,null,null,'0',4,'basic','役職等','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (5,100,1,101,null,null,null,null,null,null,4,null,null,null,'0',5,'basic','メールアドレス','','form_use',1,1,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (6,100,1,101,null,null,null,null,null,null,5,null,null,null,'0',6,'basic','電話番号','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (7,100,1,101,null,null,null,null,null,null,6,null,null,null,'0',7,'basic','郵便番号','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (8,100,1,101,null,null,null,null,null,null,7,null,null,null,'0',8,'basic','所在地','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (9,100,1,101,null,null,null,null,null,null,8,null,null,null,'0',9,'basic','その他お問い合わせ等','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (10,100,1,101,null,null,null,null,null,null,0,null,null,null,'0',1,'option','追加項目1','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (11,100,1,101,null,null,null,null,null,null,1,null,null,null,'0',2,'option','追加項目2','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (12,100,1,101,null,null,null,null,null,null,2,null,null,null,'0',3,'option','追加項目3','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (13,100,1,101,null,null,null,null,null,null,3,null,null,null,'0',4,'option','追加項目4','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (14,100,1,101,null,null,null,null,null,null,4,null,null,null,'0',5,'option','追加項目5','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (15,100,1,101,null,null,null,null,null,null,5,null,null,null,'0',6,'option','追加項目6','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (16,100,1,101,null,null,null,null,null,null,6,null,null,null,'0',7,'option','追加項目7','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (17,100,1,101,null,null,null,null,null,null,7,null,null,null,'0',8,'option','追加項目8','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (18,100,1,101,null,null,null,null,null,null,8,null,null,null,'0',9,'option','追加項目9','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (19,100,1,101,null,null,null,null,null,null,9,null,null,null,'0',10,'option','追加項目10','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (20,100,1,101,null,null,null,null,null,null,10,null,null,null,'0',11,'option','追加項目11','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (21,100,1,101,null,null,null,null,null,null,11,null,null,null,'0',12,'option','追加項目12','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (22,100,1,101,null,null,null,null,null,null,12,null,null,null,'0',13,'option','追加項目13','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (23,100,1,101,null,null,null,null,null,null,13,null,null,null,'0',14,'option','追加項目14','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (24,100,1,101,null,null,null,null,null,null,14,null,null,null,'0',15,'option','追加項目15','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (25,100,1,101,null,null,null,null,null,null,15,null,null,null,'0',16,'option','追加項目16','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (26,100,1,101,null,null,null,null,null,null,16,null,null,null,'0',17,'option','追加項目17','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (27,100,1,101,null,null,null,null,null,null,17,null,null,null,'0',18,'option','追加項目18','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (28,100,1,101,null,null,null,null,null,null,18,null,null,null,'0',19,'option','追加項目19','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
INSERT INTO t_free_form_item ( id, relation_data_type, relation_data_id, data_type, post_title, post_sub_title, post_content, post_link, post_link_text, post_status, order_number, post_date, new_icon_end_date, publish_end_date, draft_flg, column_no, column_type, title, choices, form_type, valid_flg, require_flg, del_flg, insert_user, insert_datetime, update_user, update_datetime ) VALUES (29,100,1,101,null,null,null,null,null,null,19,null,null,null,'0',20,'option','追加項目20','','',0,0,'0','nds','2013-05-01 14:38:54',null,'2013-05-01 14:38:54');
